#!/bin/bash


SCRIPT_DIR=$(readlink -m $(dirname $0))
OUT_DIR=$SCRIPT_DIR/out
ARCH=$(uname -m)


if [ "$ARCH" == "x86_64" ]; then
    export QT_HOME=/usr/local/Qt/6.2.2/gcc_64
elif [ "$ARCH" == "aarch64" ]; then
    export QT_HOME=/usr/local/Qt/6.2.2/arm64
else
    echo "Unsupported architecture: $ARCH"
    echo
    exit 1
fi


if [ $# -lt 1 ]; then
    WHAT_TO_MAKE=
elif [ "$1" == "all" ]; then
    WHAT_TO_MAKE=
elif [ "$1" == "app" ]; then
    WHAT_TO_MAKE=a.out.app
elif [ "$1" == "exp" ]; then
    WHAT_TO_MAKE=a.out.exp
elif [ "$1" == "gtest" ]; then
    WHAT_TO_MAKE=a.out.gtest
else
    echo "Must build either 'app', 'exp', 'gtest', or 'all'"
    echo
    exit 1
fi


if [ ! -e $OUT_DIR ]; then
    mkdir $OUT_DIR
fi


PROJECT_LIB_DIR=$SCRIPT_DIR/lib/$ARCH


cd $OUT_DIR
cmake -DICS46_PROJECT_LIB_DIR=$PROJECT_LIB_DIR $SCRIPT_DIR


if [ $? -eq 0 ]; then
    make $WHAT_TO_MAKE
fi

